# Generated by Django 5.2.7 on 2025-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='John')),
                ('surname', models.CharField(max_length=200, verbose_name='smith')),
                ('birth_year', models.DateField(verbose_name='1998 Year')),
                ('birth_month', models.DateField(verbose_name='7 Month')),
                ('birth_day', models.DateField(verbose_name='24 Day')),
                ('adress', models.CharField(max_length=200, verbose_name='bla bla')),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254, verbose_name='Email@gmail.com')),
            ],
        ),
    ]
