# Generated by Django 5.2.7 on 2025-11-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='other', max_length=8),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='birth_day',
            field=models.DateField(verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='birth_month',
            field=models.DateField(verbose_name='Birth Month'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='birth_year',
            field=models.DateField(verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Surname'),
        ),
    ]
