# Generated by Django 5.2.7 on 2025-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_contactinfo_gender_contactinfo_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='user_gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], default='other', max_length=8),
        ),
    ]
