# Generated by Django 5.2.7 on 2025-11-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_contactinfo_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='birth_year',
        ),
    ]
