# Generated by Django 5.2.7 on 2025-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_upvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
